"""Download the brand typefaces into the app, to be served from our own origin.

Not a <link> to Google Fonts, for two reasons that both matter here. The
service worker precaches the app shell so a capture screen opens with no
connection, and a stylesheet fetched from someone else's domain is the one
part of that shell that would not be there. And a font request carries the
child's IP to a third party on every cold load, which is a strange thing for
an app whose entire argument is that their video never leaves the phone.

Latin and Latin Extended only. Extended is not optional -- the app ships in
Spanish and the accents live there.

    python3 scripts/fetch_app_fonts.py
"""
from __future__ import annotations

import pathlib
import re
import subprocess
import sys

OUT = pathlib.Path(__file__).parent.parent / "offdays" / "web" / "static" / "fonts"
CA = "/root/.ccr/ca-bundle.crt"
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/124.0.0.0 Safari/537.36")

#: Only the weights the stylesheet actually asks for. Every extra face is
#: bytes down a phone connection in a garden.
FAMILIES = {
    "Barlow+Condensed:wght@600;700": "barlow-condensed",
    "Inter:wght@400;500;600": "inter",
    "JetBrains+Mono:wght@400": "jetbrains-mono",
}
KEEP = ("latin", "latin-ext")


def get(url: str) -> bytes:
    r = subprocess.run(["curl", "-sS", "--fail", "--cacert", CA, "-A", UA, url],
                       capture_output=True)
    if r.returncode:
        raise SystemExit(f"fetch failed: {url}\n{r.stderr.decode()[:300]}")
    return r.stdout


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    faces: list[str] = []
    for family, slug in FAMILIES.items():
        css = get(f"https://fonts.googleapis.com/css2?family={family}&display=swap").decode()
        # Google emits one @font-face per (weight, unicode subset), each
        # preceded by a /* subset */ comment. Keep the Latin ones.
        blocks = re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.S)
        for subset, block in blocks:
            if subset not in KEEP:
                continue
            weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
            url = re.search(r"url\((https://[^)]+)\)", block).group(1)
            name = f"{slug}-{weight}-{subset}.woff2"
            (OUT / name).write_bytes(get(url))
            # Relative to fonts.css, which lives in this directory -- not to
            # styles.css, which is a level up and imports it.
            faces.append(block.replace(url, name).strip())
    (OUT / "fonts.css").write_text(
        "/* Generated by scripts/fetch_app_fonts.py. Do not edit. */\n"
        + "\n".join(faces) + "\n")
    total = sum(f.stat().st_size for f in OUT.glob("*.woff2"))
    print(f"{len(faces)} faces, {total // 1024}KB of woff2 in {OUT}")
    for f in sorted(OUT.glob("*.woff2")):
        print(f"  {f.name:38} {f.stat().st_size // 1024}KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
